services.hypridle = {
  enable = true;
  settings = {
    # General settings (lock and wake)
    general = {
      before_sleep_cmd = "hyprlock";
      after_sleep_cmd = "hyprctl dispatch dpms on";
    };
    # Timeout listeners
    listener = [
      {
        timeout = 600; # 10 min
        on-timeout = "hyprlock";
      }
      {
        timeout = 1800; # 30 min
        on-timeout = "systemctl suspend";
      }
    ];
  };
};

